### ISSUE TITLE
Sci-kit learn compatibility wrt centroid location.

### ISSUE THREAD

**Issue by stephantul** [bm424/scikit-cmeans#1]
In `sklearn.cluster.KMeans`, the centroids are located in an attribute called `cluster_centers_`. In this package, these are located in `centers`. 

For uniformity, we could add `cluster_centers_` to the package, in addition to `centers`. This would preserve backward compatibility but also makes this package a drop-in replacement for `sklearn`'s `KMeans`.

**Comment by stephantul** [comment]
I can add the functionality, but I would like to discuss whether you think this is a good idea.

**Comment by bm424** [comment]
Hey @stephantul ! Sorry I was very slow getting back to this, but I think that's an excellent idea. Let me know if you still want to do it, otherwise as you say it's not difficult and I'll get around to it myself.

**Comment by stephantul** [comment]
Hey @bm424, thanks for the response! 
I'm quite busy right now (is anyone _not_ busy?), but I might have time in a couple of weeks.
If you're up for it, go ahead, I think it would be a great addition!

**Comment by bm424** [comment]
> (is anyone not busy?)

Such is life. I'm on it then!

**Comment by bm424** [comment]
Implemented in 212cde0
